# Default values for jfrog-platform

# nameOverride:
# fullnameOverride:

global:
  ## Artifactory UI URL - Mandatory
  ## Update jfrogUrlUI before running builds on Pipelines
  ## This must be the external URL of Artifactory that any service (such as scm provider) and buildnodes
  ## that you're using can access, for example: https://artifactory.example.com
  ## This is a test url and must be changed before running any builds
  jfrogUrlUI: https://mgt-artifact1.th-mgt.local

  joinKey: NOTAREALJOINKEY
  masterKey: NOTAREALMASTERKEY

  database:
    host: "{{ .Release.Name }}-postgresql"
    port: 5432
    sslMode: disable
    adminUsername: postgres
    adminPassword: postgres
    secrets: {}
      # adminUsername:
      #   name: "jp-database-creds"
      #   key: "db-admin-user"
      # adminPassword:
      #   name: "jp-database-creds"
      #   key: "db-admin-password"
    initContainerSetupDBImage: releases-docker.jfrog.io/postgres:13.10-alpine
    # Run the postgres init container as a non-default uid
    initContainerSetupDBUser:
    initContainerImagePullPolicy: Always
    # If you are using external postgresql, set initDBCreation: false
    initDBCreation: true

## This Postgresql is used by all products , set postgresql.enabled: false, when you want to use external postgresql for all products
postgresql:
  enabled: false

## This Rabbitmq is used by Xray and Pipelines only, set rabbitmq.enabled: false, when Xray or Pipelines is not enabled
rabbitmq:
  enabled: true
  auth:
    username: admin
    password: password
    erlangCookie: secretcookie
  persistence:
    size: 50Gi

## This Redis is used by pipelines only, set redis.enabled: false, when pipelines is not enabled
redis:
  enabled: false

artifactory:
  enabled: true
  database:
    type: postgresql
    driver: org.postgresql.Driver
    url: jdbc:postgresql://pgjfrog-primary.jfrog.svc:5432/ARTIFACTORY_DATABASE
    secrets: 
      adminUsername:
        name: "pgjfrog-pguser-jfrogartifactory"
        key: "user"
      adminPassword:
        name: "pgjfrog-pguser-jfrogartifactory"
        key: "password"
  ingress:
    enabled: true
    defaultBackend:
      enabled: true
    hosts: 
      - mgt-artifact1.th-mgt.local
    annotations: 
      kubernetes.io/ingress.class: "nginx"
  # tls: 
  # - secretName: nginx-tls
  #   hosts:
  #     - <nginx-ingress-svc-external-hostname or dns hostname>
  # Note: For artifactory Pro license, mission-control is not supported, Hence, set mc.enabled: false
  mc:
    enabled: true
  artifactory:
    # Note: For HA deployments, set replicaCount >1 (recommended 3)
    replicaCount: 3
    migration:
      enabled: false
    persistence:
      size: 200Gi
    # license:
    #   secret:
    #   dataKey:

xray:
  enabled: true
  postgresql:
    enabled: false
  database:
    type: postgresql
    driver: org.postgresql.Driver
    url: jdbc:postgresql://pgjfrog-primary.jfrog.svc:5432/XRAY_DATABASE
    secrets: 
      adminUsername:
        name: "pgjfrog-pguser-jfrogxray"
        key: "user"
      adminPassword:
        name: "pgjfrog-pguser-jfrogxray"
        key: "password"
  common:
    persistence:
      size: 200Gi

distribution:
  enabled: true
  unifiedUpgradeAllowed: true
  postgresql:
    enabled: false
  database:
    type: postgresql
    driver: org.postgresql.Driver
    url: jdbc:postgresql://pgjfrog-primary.jfrog.svc:5432/DISTRIBUTION_DATABASE
    secrets: 
      adminUsername:
        name: "pgjfrog-pguser-jfrogdistribution"
        key: "user"
      adminPassword:
        name: "pgjfrog-pguser-jfrogdistribution"
        key: "password"

insight:
  enabled: true
  unifiedUpgradeAllowed: true
  postgresql:
    enabled: false
  database:
    type: postgresql
    driver: org.postgresql.Driver
    url: jdbc:postgresql://pgjfrog-primary.jfrog.svc:5432/INSIGHT_DATABASE
    secrets: 
      adminUsername:
        name: "pgjfrog-pguser-jfroginsight"
        key: "user"
      adminPassword:
        name: "pgjfrog-pguser-jfroginsight"
        key: "password"
  elasticsearch:
    javaOpts:
      xms: "2g"
      xmx: "2g"

pipelines:
  enabled: false

pdnServer:
  enabled: false